# Build settings
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed

sass:
  style: :compressed

timezone: Europe/Stockholm
permalink: /posts/:title
exclude: [Gemfile, Gemfile.lock, README.md, LICENSE]

# Site settings
title: Mikael Mattsson
description: Codes and stuff
email: mikael.p.mattsson@gmail.com
twitter:
baseUrl: "/"
url: "https://mikaelmattsson.github.io"
