# Build settings
gems:
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed

sass:
  style: :compressed

timezone: Europe/Stockholm
permalink: /posts/:title
exclude: [Gemfile, Gemfile.lock, README.md, LICENSE]

# Site settings
title: Vincent Klaiber
description: Articles on everyday programming, personal challenges and new fun tech news.
email: hello@vinkla.com
twitter: vnkla
baseUrl: "/"
url: "https://vinkla.com"
