gems:
  - jekyll-redirect-from
  - jekyll-sitemap

name: Vincent Klaiber
author: Vincent Klaiber
timezone: Europe/Stockholm

twitter: https://twitter.com/vnkla

google:
  key: k1b2WlZeQuK2T7X1vY_9IdacPqNuT56rQCJbNDbg0dI
