gems:
  - jekyll-sitemap

timezone: Europe/Stockholm
exclude: [Gemfile, Gemfile.lock, RE ADME.md]

baseUrl: "/"
url: "http://vinkla.com"

permalink: /:year/:month/:title

author: Vincent Klaiber
email: me@vinkla.com

twitter: vnkla

sass:
  style: :compressed
