# Build settings
gems:
  - jekyll-sitemap
  - jekyll-redirect-from

sass:
  style: :compressed

timezone: Europe/Stockholm
permalink: /posts/:title
exclude: [Gemfile, Gemfile.lock, RE ADME.md]

# Site settings
title: Vincent Klaiber
email: hello@vinkla.com
description: Articles on everyday programming, personal challenges and new fun tech news.
twitter: vnkla
baseUrl: "/"
url: "http://vinkla.com"
